### ISSUE TITLE
Serialize Items & ItemContainers

### ISSUE THREAD

**Issue by shadowlerone** [Trim0500/DnD-Character-Creation#38]

**Comment by Trim0500** [comment]
---
### Brainstorm
- Thinking about it, I need to make 2 kinds of CSV files, 1 for Item and 1 for ItemContainers. In each case, a struct can be used to define how a record should look like in a CSV file. In this struct, the fields that make up the classes would be included but because there is a direct relationship with Maps & Characters, these records should use "foreign keys".
- 2 CSV files should be made:
    - SavedItems.csv
    - SavedItemContainers.csv
- The CSV files will be stored in a folder in the project directory: "SavedItems"
- The following defines what the new Structs and records will look like
    - ItemRecord
        - ItemId: int << primary key >>
        - containerId: int << foreign key >>
        - itemName: string
        - enchantmentBonus: int
        - itemtype: int
        - enchantmentType: int
        - weight: float
    - ItemContainerRecord
        - containerId: int << primary key >>
        - characterId: int? << foreign key >>
        - mapCellId: int? << foreign key >>
        - itemName: string
        - enchantmentBonus: int
        - itemtype: int
        - enchantmentType: int
        - weight: float
        - capacity: float

### Note
- The item containers have a direct relationship with characters and maps. The former being that 2 types of containers can exist for a character (Worn Items & Backpack) while the latter may have a special cell that has a chest placed on it. @wokidoo @Polomich Please take note of the foreign key relationships in these records and CSV files.
---

**Comment by Trim0500** [comment]
---
### Functionality
- Load
    - Simply find the contents of a specific file (be it for items or containers)
        - If the file exists, slurp the contents and build up the items and containers in memory
        - If the file doesn't exist, throw an exception
- Save
    - Check if a file exists first
        - If the file exists, load the contents into a list, search the contents to see if matches exist for updates, then build up the contents to save into the csv and override the contents
        - If the file doesn't exist, build up the csv contents to save and create the file
---

**Comment by Trim0500** [comment]
---
- Made a branch for this issue: [Story/COMP345-A2_--_Serialize_Items](https://github.com/Trim0500/DnD-Character-Creation/tree/Story/COMP345-A2-38_--_Serialize_Items)
---

**Comment by Trim0500** [comment]
---
- So for saving the item containers, I need to map cell ids to be implemented and at this moment that doesn't exist. I'll open up an issue for it and link it here. Until that gets settled and the code is put into the changes brought up in this issue, it'll remain open.
---
